# Generated by Django 4.2.6 on 2023-10-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='username',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(default='', max_length=255, unique=True),
        ),
    ]
