# Generated by Django 4.2.7 on 2023-11-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_sections_servicegroups_usermodel_sections_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='sections',
            field=models.ManyToManyField(blank=True, to='users.sections'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='service_groups',
            field=models.ManyToManyField(blank=True, to='users.servicegroups'),
        ),
    ]
