# Generated by Django 4.2.7 on 2023-11-15 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usermodel_sections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='section_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='user_sections', to='users.sections'),
        ),
    ]
